/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
var anim=[
    {
        id:0,
        img:'chat-icons/heart.png',
        value:'<3'
    },
    {
        id:1,
        img:'chat-icons/kiki.png',
        value:'^_^'
    },
    {
        id:2,
        img:'chat-icons/squint.png',
        value:'-_-'
    },
    {
        id:3,
        img:'chat-icons/confused.png',
        value:'o.O'
    },
    {
        id:4,
        img:'chat-icons/upset.png',
        value:'>:O'
    },
    {
        id:5,
        img:'chat-icons/pacman.png',
        value:':v'
    },
    {
        id:6,
        img:'chat-icons/colonthree.png',
        value:':3'
    },
    {
        id:7,
        img:'chat-icons/kiss.png',
        value:':*'
    },
    {
        id:8,
        img:'chat-icons/angel.png',
        value:'O:)'
    },
    {
        id:9,
        img:'chat-icons/devil.png',
        value:'3:)'
    },
    {
        id:10,
        img:'chat-icons/cry.png',
        value:">:'("
    },
    {
        id:11,
        img:'chat-icons/unsure.png',
        value:'>:/'
    },
    {
        id:12,
        img:'chat-icons/grumpy.png',
        value:'>:-('
    },
    {
        id:13,
        img:'chat-icons/sunglasses.png',
        value:'8|'
    },
    {
        id:14,
        img:'chat-icons/glasses.png',
        value:'8)'
    },
    {
        id:15,
        img:'chat-icons/wink.png',
        value:';)'
    },
    {
        id:16,
        img:'chat-icons/gasp.png',
        value:':O'
    },
    {
        id:17,
        img:'chat-icons/grin.png',
        value:':D'
    },
    {
        id:18,
        img:'chat-icons/tongue.png',
        value:':p'
    },
    {
        id:19,
        img:'chat-icons/frown.png',
        value:':('
    },
    {
        id:20,
        img:'chat-icons/smile.png',
        value:':)'
    }
]
